### ISSUE TITLE
[bug] translation output is truncated for key-object

### ISSUE THREAD

**Issue by anthonyronda** [1000nettles/foundry-magic-l18n#1]
After consulting with @1000nettles, this package was made with a strict `"key" : "string"` JSON structure in mind. Some foundry packages use a structure like so.

```json
{
    "packagename-key" : {
        "string-key": "string-value to be translated"
    }
}
```

foundry-magic-l10n currently doesn't support this. It seems to output only the first string value for each object.

**Comment by 1000nettles** [comment]
Now fixed in the latest version of the module. All generated language files will be flattened in their output just FYI.

Check out this download bundle for Forien's Quest Log: https://foundry-magic-l10n.s3.amazonaws.com/downloads/e4ccffe8-ab52-4e0d-be83-fababd9a2613.zip

(Using the manifest URL https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/releases/download/0.7.2/module.json
